# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=12)),
                ('block_pkt', models.FileField(upload_to='')),
                ('atk_type', models.TextField()),
                ('pkt_time', models.DateTimeField(blank=True, null=True)),
                ('block_stat', models.BooleanField(default='False')),
            ],
        ),
    ]
